let flags = [
  "SDL_WINDOWEVENT_SHOWN";
  "SDL_WINDOWEVENT_HIDDEN";
  "SDL_WINDOWEVENT_EXPOSED";
  "SDL_WINDOWEVENT_MOVED";
  "SDL_WINDOWEVENT_RESIZED";
  "SDL_WINDOWEVENT_SIZE_CHANGED";
  "SDL_WINDOWEVENT_MINIMIZED";
  "SDL_WINDOWEVENT_MAXIMIZED";
  "SDL_WINDOWEVENT_RESTORED";
  "SDL_WINDOWEVENT_ENTER";
  "SDL_WINDOWEVENT_LEAVE";
  "SDL_WINDOWEVENT_FOCUS_GAINED";
  "SDL_WINDOWEVENT_FOCUS_LOST";
  "SDL_WINDOWEVENT_CLOSE";
]

let () =
  ignore (List.fold_left (fun n flag ->
    Printf.printf "#define MLTAG_%s (%d)\n" flag n;
    succ n
  ) 0 flags)
