CAMLprim value gl_api_glAccum(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glAccum can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glAlphaFunc(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glAlphaFunc can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glAreTexturesResident(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glAreTexturesResident can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glArrayElement(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glArrayElement can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glBegin(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glBegin can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glBitmap(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glBitmap can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glCallList(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glCallList can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glCallLists(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glCallLists can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glClearAccum(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glClearAccum can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glClearIndex(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glClearIndex can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glClipPlane(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glClipPlane can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glClipPlanei(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glClipPlanei can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glColorMaterial(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glColorMaterial can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glColorPointer(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glColorPointer can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glColor3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glColor3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glColor4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glColor4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glColor3v(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glColor3v can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glColor4v(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glColor4v can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glConvolutionParameter(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glConvolutionParameter can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glConvolutionParameter_border(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glConvolutionParameter_border can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glCopyConvolutionFilter1D(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glCopyConvolutionFilter1D can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glCopyConvolutionFilter2D(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glCopyConvolutionFilter2D can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glCopyPixels(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glCopyPixels can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glDeleteLists(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glDeleteLists can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glDisableClientState(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glDisableClientState can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glDrawPixels(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glDrawPixels can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glEdgeFlag(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glEdgeFlag can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glEdgeFlagPointer(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glEdgeFlagPointer can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glEnableClientState(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glEnableClientState can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glEnd(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glEnd can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glEndList(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glEndList can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glEvalCoord1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glEvalCoord1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glEvalCoord2(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glEvalCoord2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glEvalMesh1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glEvalMesh1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glEvalMesh2(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glEvalMesh2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glEvalPoint1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glEvalPoint1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glEvalPoint2(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glEvalPoint2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glFog1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glFog1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glFog4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glFog4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glFog_mode(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glFog_mode can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glFrustum(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glFrustum can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGenLists(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGenLists can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetClipPlane(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetClipPlane can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetLight1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetLight1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetLight3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetLight3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetLight4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetLight4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetMap(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetMap can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetMaterialf1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetMaterialf1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetMaterialf3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetMaterialf3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetMaterialf4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetMaterialf4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetPixelMap(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetPixelMap can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetPolygonStipple(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetPolygonStipple can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetTexEnv1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetTexEnv1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetTexEnv4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetTexEnv4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetTexGen1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetTexGen1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetTexGen4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetTexGen4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glGetTexImage(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glGetTexImage can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glHistogram(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glHistogram can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glIndex(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glIndex can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glIsList(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glIsList can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glIndexMask(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glIndexMask can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glIndexPointer(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glIndexPointer can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glInitNames(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glInitNames can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glLight1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glLight1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glLight3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glLight3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glLight4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glLight4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glLightModel1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glLightModel1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glLightModel4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glLightModel4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glLightModelControl(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glLightModelControl can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glLineStipple(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glLineStipple can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glListBase(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glListBase can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glLoadIdentity(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glLoadIdentity can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glLoadMatrix(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glLoadMatrix can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glLoadName(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glLoadName can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glLoadTransposeMatrix(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glLoadTransposeMatrix can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMap1_1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMap1_1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMap1_2(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMap1_2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMap1_3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMap1_3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMap1_4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMap1_4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMap2_1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMap2_1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMap2_2(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMap2_2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMap2_3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMap2_3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMap2_4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMap2_4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMapGrid1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMapGrid1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMapGrid2(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMapGrid2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMaterial1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMaterial1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMaterial3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMaterial3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMaterial4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMaterial4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMatrixMode(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMatrixMode can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMultMatrix(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMultMatrix can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMultTransposeMatrix(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMultTransposeMatrix can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMultiTexCoord1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMultiTexCoord1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMultiTexCoord2(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMultiTexCoord2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMultiTexCoord3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMultiTexCoord3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glMultiTexCoord4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glMultiTexCoord4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glNewList(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glNewList can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glNormal(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glNormal can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glNormalPointer(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glNormalPointer can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glNormalv(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glNormalv can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glOrtho(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glOrtho can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glOrtho_bytecode(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glOrtho can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPixelMap(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPixelMap can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPixelTransferb(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPixelTransferb can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPixelTransferf(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPixelTransferf can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPixelTransferi(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPixelTransferi can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPixelZoom(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPixelZoom can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPolygonStipple(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPolygonStipple can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPopAttrib(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPopAttrib can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPopClientAttrib(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPopClientAttrib can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPopMatrix(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPopMatrix can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPopName(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPopName can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPrioritizeTextures(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPrioritizeTextures can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPushAttrib(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPushAttrib can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPushClientAttrib(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPushClientAttrib can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPushMatrix(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPushMatrix can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glPushName(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glPushName can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glRasterPos2(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glRasterPos2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glRasterPos3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glRasterPos3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glRasterPos4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glRasterPos4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glRect(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glRect can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glRenderMode(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glRenderMode can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glResetHistogram(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glResetHistogram can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glRotate(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glRotate can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glScale(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glScale can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glSelectBuffer(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glSelectBuffer can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glShadeModel(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glShadeModel can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexCoord1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexCoord1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexCoord2(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexCoord2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexCoord3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexCoord3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexCoord4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexCoord4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexCoordPointer1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexCoordPointer1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexCoordPointer2(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexCoordPointer2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexCoordPointer3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexCoordPointer3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexCoordPointer4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexCoordPointer4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexEnv1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexEnv1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexEnv4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexEnv4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexGen1(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexGen1 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTexGen4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTexGen4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glTranslate(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glTranslate can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glVertex2(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glVertex2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glVertex2v(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glVertex2v can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glVertex3(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glVertex3 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glVertex3v(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glVertex3v can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glVertex4(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glVertex4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glVertex4v(value unit) {
  CAMLparam1(unit);
  caml_failwith("gl_api_glVertex4v can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glVertexPointer2(value pointer_type, value stride, value pointer) {
  CAMLparam3(pointer_type, stride, pointer);
  caml_failwith("gl_api_glVertexPointer2 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glVertexPointer3(value size, value pointer_type, value stride, value pointer) {
  CAMLparam3(pointer_type, stride, pointer);
  CAMLreturn(Val_unit);
}
CAMLprim value gl_api_glVertexPointer4(value size, value pointer_type, value stride, value pointer) {
  CAMLparam3(pointer_type, stride, pointer);
  caml_failwith("gl_api_glVertexPointer4 can not use in the profile of OpenGL version 3.1 above");
  CAMLreturn(Val_unit);
}
