
enum glenum {
  GFalse = 0x0,
  GTrue = 0x1,
  GByte = 0x1400,
  GShort = 0x1402,
  GInt = 0x1404,
  GFloat = 0x1406,
  GDouble = 0x140A,
  GPoints = 0x0000,
  GLines = 0x0001,
  GTriangles = 0x0004,
  GQuads = 0x0007,
  GPolygon = 0x0009,
  GV2f = 0x2A20,
  GV3f = 0x2A21,
  GModelview = 0x1700,
  GProjection = 0x1701,
  GTexture = 0x1702,
  GPoint = 0x1B00,
  GLine = 0x1B01,
  GFill = 0x1B02,
  GCw = 0x0900,
  GCcw = 0x0901,
  GFront = 0x0404,
  GBack = 0x0405,
  GCompile = 0x1300,
  GNever = 0x0200,
  GLess = 0x0201,
  GEqual = 0x0202,
  GLequal = 0x0203,
  GGreater = 0x0204,
  GNotequal = 0x0205,
  GGequal = 0x0206,
  GAlways = 0x0207,
  GLighting = 0x0B50,
  GLight0 = 0x4000,
  GLight1 = 0x4001,
  GLight2 = 0x4002,
  GLight3 = 0x4003,
  GLight4 = 0x4004,
  GLight5 = 0x4005,
  GLight6 = 0x4006,
  GLight7 = 0x4007,
  GAmbient = 0x1200,
  GDiffuse = 0x1201,
  GSpecular = 0x1202,
  GShininess = 0x1601,
  GEmission = 0x1600,
  GPosition = 0x1203,
  GFlat = 0x1D00,
  GSmooth = 0x1D01,
  GNormalize = 0x0BA1,
  GAccum = 0x0100,
  GAdd = 0x0104,
  GLoad = 0x0101,
  GMult = 0x0103,
  GReturn = 0x0102,
  GBlend = 0x0BE2,
  GZero = 0x0,
  GOne = 0x1,
  GFeedback = 0x1C01,
  GRender = 0x1C00,
  GSelect = 0x1C02,
  G2d = 0x0600,
  G3d = 0x0601,
  GFog = 0x0B60,
  GLinear = 0x2601,
  GExp = 0x0800,
  GExp2 = 0x0801,
  GClear = 0x1500,
  GSet = 0x150F,
  GCopy = 0x1503,
  GNoop = 0x1505,
  GInvert = 0x150A,
  GAnd = 0x1501,
  GNand = 0x150E,
  GOr = 0x1507,
  GNor = 0x1508,
  GXor = 0x1506,
  GEquiv = 0x1509,
  GKeep = 0x1E00,
  GReplace = 0x1E01,
  GIncr = 0x1E02,
  GDecr = 0x1E03,
  GNone = 0x0,
  GLeft = 0x0406,
  GRight = 0x0407,
  GAux0 = 0x0409,
  GAux1 = 0x040A,
  GAux2 = 0x040B,
  GAux3 = 0x040C,
  GRed = 0x1903,
  GGreen = 0x1904,
  GBlue = 0x1905,
  GAlpha = 0x1906,
  GLuminance = 0x1909,
  GDoublebuffer = 0x0C32,
  GStereo = 0x0C33,
  GBitmap = 0x1A00,
  GColor = 0x1800,
  GDepth = 0x1801,
  GStencil = 0x1802,
  GDither = 0x0BD0,
  GRgb = 0x1907,
  GRgba = 0x1908,
  GViewport = 0x0BA2,
  GCoeff = 0x0A00,
  GOrder = 0x0A01,
  GDomain = 0x0A02,
  GFastest = 0x1101,
  GNicest = 0x1102,
  GDecal = 0x2101,
  GModulate = 0x2100,
  GNearest = 0x2600,
  GRepeat = 0x2901,
  GClamp = 0x2900,
  GS = 0x2000,
  GT = 0x2001,
  GR = 0x2002,
  GQ = 0x2003,
  GVendor = 0x1F00,
  GRenderer = 0x1F01,
  GVersion = 0x1F02,
  GExtensions = 0x1F03,
  GAlpha4 = 0x803B,
  GAlpha8 = 0x803C,
  GAlpha12 = 0x803D,
  GAlpha16 = 0x803E,
  GLuminance4 = 0x803F,
  GLuminance8 = 0x8040,
  GLuminance12 = 0x8041,
  GLuminance16 = 0x8042,
  GIntensity = 0x8049,
  GIntensity4 = 0x804A,
  GIntensity8 = 0x804B,
  GIntensity12 = 0x804C,
  GIntensity16 = 0x804D,
  GRgb4 = 0x804F,
  GRgb5 = 0x8050,
  GRgb8 = 0x8051,
  GRgb10 = 0x8052,
  GRgb12 = 0x8053,
  GRgb16 = 0x8054,
  GRgba2 = 0x8055,
  GRgba4 = 0x8056,
  GRgba8 = 0x8058,
  GRgba12 = 0x805A,
  GRgba16 = 0x805B,
  GBgr = 0x80E0,
  GBgra = 0x80E1,
  GReduce = 0x8016,
  GHistogram = 0x8024,
  GMinmax = 0x802E,
  GMin = 0x8007,
  GMax = 0x8008,
  GTexture0 = 0x84C0,
  GTexture1 = 0x84C1,
  GTexture2 = 0x84C2,
  GTexture3 = 0x84C3,
  GTexture4 = 0x84C4,
  GTexture5 = 0x84C5,
  GTexture6 = 0x84C6,
  GTexture7 = 0x84C7,
  GTexture8 = 0x84C8,
  GTexture9 = 0x84C9,
  GTexture10 = 0x84CA,
  GTexture11 = 0x84CB,
  GTexture12 = 0x84CC,
  GTexture13 = 0x84CD,
  GTexture14 = 0x84CE,
  GTexture15 = 0x84CF,
  GTexture16 = 0x84D0,
  GTexture17 = 0x84D1,
  GTexture18 = 0x84D2,
  GTexture19 = 0x84D3,
  GTexture20 = 0x84D4,
  GTexture21 = 0x84D5,
  GTexture22 = 0x84D6,
  GTexture23 = 0x84D7,
  GTexture24 = 0x84D8,
  GTexture25 = 0x84D9,
  GTexture26 = 0x84DA,
  GTexture27 = 0x84DB,
  GTexture28 = 0x84DC,
  GTexture29 = 0x84DD,
  GTexture30 = 0x84DE,
  GTexture31 = 0x84DF,
  GMultisample = 0x809D,
  GSamples = 0x80A9,
  GCombine = 0x8570,
  GInterpolate = 0x8575,
  GSubtract = 0x84E7,
  GConstant = 0x8576,
  GPrevious = 0x8578,
};
typedef [set] enum glenum glenum_set;
