enum glenum {
  GVersion11 = 1,
  GVersion12 = 1,
  GVersion13 = 1,
  GArbImaging = 1,
  GFalse = 0x0,
  GTrue = 0x1,
  GByte = 0x1400,
  GUnsignedByte = 0x1401,
  GShort = 0x1402,
  GUnsignedShort = 0x1403,
  GInt = 0x1404,
  GUnsignedInt = 0x1405,
  GFloat = 0x1406,
  G2Bytes = 0x1407,
  G3Bytes = 0x1408,
  G4Bytes = 0x1409,
  GDouble = 0x140A,
  GPoints = 0x0000,
  GLines = 0x0001,
  GLineLoop = 0x0002,
  GLineStrip = 0x0003,
  GTriangles = 0x0004,
  GTriangleStrip = 0x0005,
  GTriangleFan = 0x0006,
  GQuads = 0x0007,
  GQuadStrip = 0x0008,
  GPolygon = 0x0009,
  GVertexArray = 0x8074,
  GNormalArray = 0x8075,
  GColorArray = 0x8076,
  GIndexArray = 0x8077,
  GTextureCoordArray = 0x8078,
  GEdgeFlagArray = 0x8079,
  GVertexArraySize = 0x807A,
  GVertexArrayType = 0x807B,
  GVertexArrayStride = 0x807C,
  GNormalArrayType = 0x807E,
  GNormalArrayStride = 0x807F,
  GColorArraySize = 0x8081,
  GColorArrayType = 0x8082,
  GColorArrayStride = 0x8083,
  GIndexArrayType = 0x8085,
  GIndexArrayStride = 0x8086,
  GTextureCoordArraySize = 0x8088,
  GTextureCoordArrayType = 0x8089,
  GTextureCoordArrayStride = 0x808A,
  GEdgeFlagArrayStride = 0x808C,
  GVertexArrayPointer = 0x808E,
  GNormalArrayPointer = 0x808F,
  GColorArrayPointer = 0x8090,
  GIndexArrayPointer = 0x8091,
  GTextureCoordArrayPointer = 0x8092,
  GEdgeFlagArrayPointer = 0x8093,
  GV2f = 0x2A20,
  GV3f = 0x2A21,
  GC4ubV2f = 0x2A22,
  GC4ubV3f = 0x2A23,
  GC3fV3f = 0x2A24,
  GN3fV3f = 0x2A25,
  GC4fN3fV3f = 0x2A26,
  GT2fV3f = 0x2A27,
  GT4fV4f = 0x2A28,
  GT2fC4ubV3f = 0x2A29,
  GT2fC3fV3f = 0x2A2A,
  GT2fN3fV3f = 0x2A2B,
  GT2fC4fN3fV3f = 0x2A2C,
  GT4fC4fN3fV4f = 0x2A2D,
  GMatrixMode = 0x0BA0,
  GModelview = 0x1700,
  GProjection = 0x1701,
  GTexture = 0x1702,
  GPointSmooth = 0x0B10,
  GPointSize = 0x0B11,
  GPointSizeGranularity = 0x0B13,
  GPointSizeRange = 0x0B12,
  GLineSmooth = 0x0B20,
  GLineStipple = 0x0B24,
  GLineStipplePattern = 0x0B25,
  GLineStippleRepeat = 0x0B26,
  GLineWidth = 0x0B21,
  GLineWidthGranularity = 0x0B23,
  GLineWidthRange = 0x0B22,
  GPoint = 0x1B00,
  GLine = 0x1B01,
  GFill = 0x1B02,
  GCw = 0x0900,
  GCcw = 0x0901,
  GFront = 0x0404,
  GBack = 0x0405,
  GPolygonMode = 0x0B40,
  GPolygonSmooth = 0x0B41,
  GPolygonStipple = 0x0B42,
  GEdgeFlag = 0x0B43,
  GCullFace = 0x0B44,
  GCullFaceMode = 0x0B45,
  GFrontFace = 0x0B46,
  GPolygonOffsetFactor = 0x8038,
  GPolygonOffsetUnits = 0x2A00,
  GPolygonOffsetPoint = 0x2A01,
  GPolygonOffsetLine = 0x2A02,
  GPolygonOffsetFill = 0x8037,
  GCompile = 0x1300,
  GCompileAndExecute = 0x1301,
  GListBase = 0x0B32,
  GListIndex = 0x0B33,
  GListMode = 0x0B30,
  GNever = 0x0200,
  GLess = 0x0201,
  GEqual = 0x0202,
  GLequal = 0x0203,
  GGreater = 0x0204,
  GNotequal = 0x0205,
  GGequal = 0x0206,
  GAlways = 0x0207,
  GDepthTest = 0x0B71,
  GDepthBits = 0x0D56,
  GDepthClearValue = 0x0B73,
  GDepthFunc = 0x0B74,
  GDepthRange = 0x0B70,
  GDepthWritemask = 0x0B72,
  GDepthComponent = 0x1902,
  GLighting = 0x0B50,
  GLight0 = 0x4000,
  GLight1 = 0x4001,
  GLight2 = 0x4002,
  GLight3 = 0x4003,
  GLight4 = 0x4004,
  GLight5 = 0x4005,
  GLight6 = 0x4006,
  GLight7 = 0x4007,
  GSpotExponent = 0x1205,
  GSpotCutoff = 0x1206,
  GConstantAttenuation = 0x1207,
  GLinearAttenuation = 0x1208,
  GQuadraticAttenuation = 0x1209,
  GAmbient = 0x1200,
  GDiffuse = 0x1201,
  GSpecular = 0x1202,
  GShininess = 0x1601,
  GEmission = 0x1600,
  GPosition = 0x1203,
  GSpotDirection = 0x1204,
  GAmbientAndDiffuse = 0x1602,
  GColorIndexes = 0x1603,
  GLightModelTwoSide = 0x0B52,
  GLightModelLocalViewer = 0x0B51,
  GLightModelAmbient = 0x0B53,
  GFrontAndBack = 0x0408,
  GShadeModel = 0x0B54,
  GFlat = 0x1D00,
  GSmooth = 0x1D01,
  GColorMaterial = 0x0B57,
  GColorMaterialFace = 0x0B55,
  GColorMaterialParameter = 0x0B56,
  GNormalize = 0x0BA1,
  GClipPlane0 = 0x3000,
  GClipPlane1 = 0x3001,
  GClipPlane2 = 0x3002,
  GClipPlane3 = 0x3003,
  GClipPlane4 = 0x3004,
  GClipPlane5 = 0x3005,
  GAccumRedBits = 0x0D58,
  GAccumGreenBits = 0x0D59,
  GAccumBlueBits = 0x0D5A,
  GAccumAlphaBits = 0x0D5B,
  GAccumClearValue = 0x0B80,
  GAccum = 0x0100,
  GAdd = 0x0104,
  GLoad = 0x0101,
  GMult = 0x0103,
  GReturn = 0x0102,
  GAlphaTest = 0x0BC0,
  GAlphaTestRef = 0x0BC2,
  GAlphaTestFunc = 0x0BC1,
  GBlend = 0x0BE2,
  GBlendSrc = 0x0BE1,
  GBlendDst = 0x0BE0,
  GZero = 0x0,
  GOne = 0x1,
  GSrcColor = 0x0300,
  GOneMinusSrcColor = 0x0301,
  GSrcAlpha = 0x0302,
  GOneMinusSrcAlpha = 0x0303,
  GDstAlpha = 0x0304,
  GOneMinusDstAlpha = 0x0305,
  GDstColor = 0x0306,
  GOneMinusDstColor = 0x0307,
  GSrcAlphaSaturate = 0x0308,
  GFeedback = 0x1C01,
  GRender = 0x1C00,
  GSelect = 0x1C02,
  G2d = 0x0600,
  G3d = 0x0601,
  G3dColor = 0x0602,
  G3dColorTexture = 0x0603,
  G4dColorTexture = 0x0604,
  GPointToken = 0x0701,
  GLineToken = 0x0702,
  GLineResetToken = 0x0707,
  GPolygonToken = 0x0703,
  GBitmapToken = 0x0704,
  GDrawPixelToken = 0x0705,
  GCopyPixelToken = 0x0706,
  GPassThroughToken = 0x0700,
  GFeedbackBufferPointer = 0x0DF0,
  GFeedbackBufferSize = 0x0DF1,
  GFeedbackBufferType = 0x0DF2,
  GSelectionBufferPointer = 0x0DF3,
  GSelectionBufferSize = 0x0DF4,
  GFog = 0x0B60,
  GFogMode = 0x0B65,
  GFogDensity = 0x0B62,
  GFogColor = 0x0B66,
  GFogIndex = 0x0B61,
  GFogStart = 0x0B63,
  GFogEnd = 0x0B64,
  GLinear = 0x2601,
  GExp = 0x0800,
  GExp2 = 0x0801,
  GLogicOp = 0x0BF1,
  GIndexLogicOp = 0x0BF1,
  GColorLogicOp = 0x0BF2,
  GLogicOpMode = 0x0BF0,
  GClear = 0x1500,
  GSet = 0x150F,
  GCopy = 0x1503,
  GCopyInverted = 0x150C,
  GNoop = 0x1505,
  GInvert = 0x150A,
  GAnd = 0x1501,
  GNand = 0x150E,
  GOr = 0x1507,
  GNor = 0x1508,
  GXor = 0x1506,
  GEquiv = 0x1509,
  GAndReverse = 0x1502,
  GAndInverted = 0x1504,
  GOrReverse = 0x150B,
  GOrInverted = 0x150D,
  GStencilBits = 0x0D57,
  GStencilTest = 0x0B90,
  GStencilClearValue = 0x0B91,
  GStencilFunc = 0x0B92,
  GStencilValueMask = 0x0B93,
  GStencilFail = 0x0B94,
  GStencilPassDepthFail = 0x0B95,
  GStencilPassDepthPass = 0x0B96,
  GStencilRef = 0x0B97,
  GStencilWritemask = 0x0B98,
  GStencilIndex = 0x1901,
  GKeep = 0x1E00,
  GReplace = 0x1E01,
  GIncr = 0x1E02,
  GDecr = 0x1E03,
  GNone = 0x0,
  GLeft = 0x0406,
  GRight = 0x0407,
  GFrontLeft = 0x0400,
  GFrontRight = 0x0401,
  GBackLeft = 0x0402,
  GBackRight = 0x0403,
  GAux0 = 0x0409,
  GAux1 = 0x040A,
  GAux2 = 0x040B,
  GAux3 = 0x040C,
  GColorIndex = 0x1900,
  GRed = 0x1903,
  GGreen = 0x1904,
  GBlue = 0x1905,
  GAlpha = 0x1906,
  GLuminance = 0x1909,
  GLuminanceAlpha = 0x190A,
  GAlphaBits = 0x0D55,
  GRedBits = 0x0D52,
  GGreenBits = 0x0D53,
  GBlueBits = 0x0D54,
  GIndexBits = 0x0D51,
  GSubpixelBits = 0x0D50,
  GAuxBuffers = 0x0C00,
  GReadBuffer = 0x0C02,
  GDrawBuffer = 0x0C01,
  GDoublebuffer = 0x0C32,
  GStereo = 0x0C33,
  GBitmap = 0x1A00,
  GColor = 0x1800,
  GDepth = 0x1801,
  GStencil = 0x1802,
  GDither = 0x0BD0,
  GRgb = 0x1907,
  GRgba = 0x1908,
  GMaxListNesting = 0x0B31,
  GMaxEvalOrder = 0x0D30,
  GMaxLights = 0x0D31,
  GMaxClipPlanes = 0x0D32,
  GMaxTextureSize = 0x0D33,
  GMaxPixelMapTable = 0x0D34,
  GMaxAttribStackDepth = 0x0D35,
  GMaxModelviewStackDepth = 0x0D36,
  GMaxNameStackDepth = 0x0D37,
  GMaxProjectionStackDepth = 0x0D38,
  GMaxTextureStackDepth = 0x0D39,
  GMaxViewportDims = 0x0D3A,
  GMaxClientAttribStackDepth = 0x0D3B,
  GAttribStackDepth = 0x0BB0,
  GClientAttribStackDepth = 0x0BB1,
  GColorClearValue = 0x0C22,
  GColorWritemask = 0x0C23,
  GCurrentIndex = 0x0B01,
  GCurrentColor = 0x0B00,
  GCurrentNormal = 0x0B02,
  GCurrentRasterColor = 0x0B04,
  GCurrentRasterDistance = 0x0B09,
  GCurrentRasterIndex = 0x0B05,
  GCurrentRasterPosition = 0x0B07,
  GCurrentRasterTextureCoords = 0x0B06,
  GCurrentRasterPositionValid = 0x0B08,
  GCurrentTextureCoords = 0x0B03,
  GIndexClearValue = 0x0C20,
  GIndexMode = 0x0C30,
  GIndexWritemask = 0x0C21,
  GModelviewMatrix = 0x0BA6,
  GModelviewStackDepth = 0x0BA3,
  GNameStackDepth = 0x0D70,
  GProjectionMatrix = 0x0BA7,
  GProjectionStackDepth = 0x0BA4,
  GRenderMode = 0x0C40,
  GRgbaMode = 0x0C31,
  GTextureMatrix = 0x0BA8,
  GTextureStackDepth = 0x0BA5,
  GViewport = 0x0BA2,
  GAutoNormal = 0x0D80,
  GMap1Color4 = 0x0D90,
  GMap1Index = 0x0D91,
  GMap1Normal = 0x0D92,
  GMap1TextureCoord1 = 0x0D93,
  GMap1TextureCoord2 = 0x0D94,
  GMap1TextureCoord3 = 0x0D95,
  GMap1TextureCoord4 = 0x0D96,
  GMap1Vertex3 = 0x0D97,
  GMap1Vertex4 = 0x0D98,
  GMap2Color4 = 0x0DB0,
  GMap2Index = 0x0DB1,
  GMap2Normal = 0x0DB2,
  GMap2TextureCoord1 = 0x0DB3,
  GMap2TextureCoord2 = 0x0DB4,
  GMap2TextureCoord3 = 0x0DB5,
  GMap2TextureCoord4 = 0x0DB6,
  GMap2Vertex3 = 0x0DB7,
  GMap2Vertex4 = 0x0DB8,
  GMap1GridDomain = 0x0DD0,
  GMap1GridSegments = 0x0DD1,
  GMap2GridDomain = 0x0DD2,
  GMap2GridSegments = 0x0DD3,
  GCoeff = 0x0A00,
  GOrder = 0x0A01,
  GDomain = 0x0A02,
  GPerspectiveCorrectionHint = 0x0C50,
  GPointSmoothHint = 0x0C51,
  GLineSmoothHint = 0x0C52,
  GPolygonSmoothHint = 0x0C53,
  GFogHint = 0x0C54,
  GDontCare = 0x1100,
  GFastest = 0x1101,
  GNicest = 0x1102,
  GScissorBox = 0x0C10,
  GScissorTest = 0x0C11,
  GMapColor = 0x0D10,
  GMapStencil = 0x0D11,
  GIndexShift = 0x0D12,
  GIndexOffset = 0x0D13,
  GRedScale = 0x0D14,
  GRedBias = 0x0D15,
  GGreenScale = 0x0D18,
  GGreenBias = 0x0D19,
  GBlueScale = 0x0D1A,
  GBlueBias = 0x0D1B,
  GAlphaScale = 0x0D1C,
  GAlphaBias = 0x0D1D,
  GDepthScale = 0x0D1E,
  GDepthBias = 0x0D1F,
  GPixelMapSToSSize = 0x0CB1,
  GPixelMapIToISize = 0x0CB0,
  GPixelMapIToRSize = 0x0CB2,
  GPixelMapIToGSize = 0x0CB3,
  GPixelMapIToBSize = 0x0CB4,
  GPixelMapIToASize = 0x0CB5,
  GPixelMapRToRSize = 0x0CB6,
  GPixelMapGToGSize = 0x0CB7,
  GPixelMapBToBSize = 0x0CB8,
  GPixelMapAToASize = 0x0CB9,
  GPixelMapSToS = 0x0C71,
  GPixelMapIToI = 0x0C70,
  GPixelMapIToR = 0x0C72,
  GPixelMapIToG = 0x0C73,
  GPixelMapIToB = 0x0C74,
  GPixelMapIToA = 0x0C75,
  GPixelMapRToR = 0x0C76,
  GPixelMapGToG = 0x0C77,
  GPixelMapBToB = 0x0C78,
  GPixelMapAToA = 0x0C79,
  GPackAlignment = 0x0D05,
  GPackLsbFirst = 0x0D01,
  GPackRowLength = 0x0D02,
  GPackSkipPixels = 0x0D04,
  GPackSkipRows = 0x0D03,
  GPackSwapBytes = 0x0D00,
  GUnpackAlignment = 0x0CF5,
  GUnpackLsbFirst = 0x0CF1,
  GUnpackRowLength = 0x0CF2,
  GUnpackSkipPixels = 0x0CF4,
  GUnpackSkipRows = 0x0CF3,
  GUnpackSwapBytes = 0x0CF0,
  GZoomX = 0x0D16,
  GZoomY = 0x0D17,
  GTextureEnv = 0x2300,
  GTextureEnvMode = 0x2200,
  GTexture1d = 0x0DE0,
  GTexture2d = 0x0DE1,
  GTextureWrapS = 0x2802,
  GTextureWrapT = 0x2803,
  GTextureMagFilter = 0x2800,
  GTextureMinFilter = 0x2801,
  GTextureEnvColor = 0x2201,
  GTextureGenS = 0x0C60,
  GTextureGenT = 0x0C61,
  GTextureGenR = 0x0C62,
  GTextureGenQ = 0x0C63,
  GTextureGenMode = 0x2500,
  GTextureBorderColor = 0x1004,
  GTextureWidth = 0x1000,
  GTextureHeight = 0x1001,
  GTextureBorder = 0x1005,
  GTextureComponents = 0x1003,
  GTextureRedSize = 0x805C,
  GTextureGreenSize = 0x805D,
  GTextureBlueSize = 0x805E,
  GTextureAlphaSize = 0x805F,
  GTextureLuminanceSize = 0x8060,
  GTextureIntensitySize = 0x8061,
  GNearestMipmapNearest = 0x2700,
  GNearestMipmapLinear = 0x2702,
  GLinearMipmapNearest = 0x2701,
  GLinearMipmapLinear = 0x2703,
  GObjectLinear = 0x2401,
  GObjectPlane = 0x2501,
  GEyeLinear = 0x2400,
  GEyePlane = 0x2502,
  GSphereMap = 0x2402,
  GDecal = 0x2101,
  GModulate = 0x2100,
  GNearest = 0x2600,
  GRepeat = 0x2901,
  GClamp = 0x2900,
  GS = 0x2000,
  GT = 0x2001,
  GR = 0x2002,
  GQ = 0x2003,
  GVendor = 0x1F00,
  GRenderer = 0x1F01,
  GVersion = 0x1F02,
  GExtensions = 0x1F03,
  GNoError = 0x0,
  GInvalidEnum = 0x0500,
  GInvalidValue = 0x0501,
  GInvalidOperation = 0x0502,
  GStackOverflow = 0x0503,
  GStackUnderflow = 0x0504,
  GOutOfMemory = 0x0505,
  GCurrentBit = 0x00000001,
  GPointBit = 0x00000002,
  GLineBit = 0x00000004,
  GPolygonBit = 0x00000008,
  GPolygonStippleBit = 0x00000010,
  GPixelModeBit = 0x00000020,
  GLightingBit = 0x00000040,
  GFogBit = 0x00000080,
  GDepthBufferBit = 0x00000100,
  GAccumBufferBit = 0x00000200,
  GStencilBufferBit = 0x00000400,
  GViewportBit = 0x00000800,
  GTransformBit = 0x00001000,
  GEnableBit = 0x00002000,
  GColorBufferBit = 0x00004000,
  GHintBit = 0x00008000,
  GEvalBit = 0x00010000,
  GListBit = 0x00020000,
  GTextureBit = 0x00040000,
  GScissorBit = 0x00080000,
  GAllAttribBits = 0x000FFFFF,
  GProxyTexture1d = 0x8063,
  GProxyTexture2d = 0x8064,
  GTexturePriority = 0x8066,
  GTextureResident = 0x8067,
  GTextureBinding1d = 0x8068,
  GTextureBinding2d = 0x8069,
  GTextureInternalFormat = 0x1003,
  GAlpha4 = 0x803B,
  GAlpha8 = 0x803C,
  GAlpha12 = 0x803D,
  GAlpha16 = 0x803E,
  GLuminance4 = 0x803F,
  GLuminance8 = 0x8040,
  GLuminance12 = 0x8041,
  GLuminance16 = 0x8042,
  GLuminance4Alpha4 = 0x8043,
  GLuminance6Alpha2 = 0x8044,
  GLuminance8Alpha8 = 0x8045,
  GLuminance12Alpha4 = 0x8046,
  GLuminance12Alpha12 = 0x8047,
  GLuminance16Alpha16 = 0x8048,
  GIntensity = 0x8049,
  GIntensity4 = 0x804A,
  GIntensity8 = 0x804B,
  GIntensity12 = 0x804C,
  GIntensity16 = 0x804D,
  GR3G3B2 = 0x2A10,
  GRgb4 = 0x804F,
  GRgb5 = 0x8050,
  GRgb8 = 0x8051,
  GRgb10 = 0x8052,
  GRgb12 = 0x8053,
  GRgb16 = 0x8054,
  GRgba2 = 0x8055,
  GRgba4 = 0x8056,
  GRgb5A1 = 0x8057,
  GRgba8 = 0x8058,
  GRgb10A2 = 0x8059,
  GRgba12 = 0x805A,
  GRgba16 = 0x805B,
  GClientPixelStoreBit = 0x00000001,
  GClientVertexArrayBit = 0x00000002,
  GAllClientAttribBits = 0xFFFFFFFF,
  GClientAllAttribBits = 0xFFFFFFFF,
  GRescaleNormal = 0x803A,
  GClampToEdge = 0x812F,
  GMaxElementsVertices = 0x80E8,
  GMaxElementsIndices = 0x80E9,
  GBgr = 0x80E0,
  GBgra = 0x80E1,
  GUnsignedByte332 = 0x8032,
  GUnsignedByte233Rev = 0x8362,
  GUnsignedShort565 = 0x8363,
  GUnsignedShort565Rev = 0x8364,
  GUnsignedShort4444 = 0x8033,
  GUnsignedShort4444Rev = 0x8365,
  GUnsignedShort5551 = 0x8034,
  GUnsignedShort1555Rev = 0x8366,
  GUnsignedInt8888 = 0x8035,
  GUnsignedInt8888Rev = 0x8367,
  GUnsignedInt1010102 = 0x8036,
  GUnsignedInt2101010Rev = 0x8368,
  GLightModelColorControl = 0x81F8,
  GSingleColor = 0x81F9,
  GSeparateSpecularColor = 0x81FA,
  GTextureMinLod = 0x813A,
  GTextureMaxLod = 0x813B,
  GTextureBaseLevel = 0x813C,
  GTextureMaxLevel = 0x813D,
  GSmoothPointSizeRange = 0x0B12,
  GSmoothPointSizeGranularity = 0x0B13,
  GSmoothLineWidthRange = 0x0B22,
  GSmoothLineWidthGranularity = 0x0B23,
  GAliasedPointSizeRange = 0x846D,
  GAliasedLineWidthRange = 0x846E,
  GPackSkipImages = 0x806B,
  GPackImageHeight = 0x806C,
  GUnpackSkipImages = 0x806D,
  GUnpackImageHeight = 0x806E,
  GTexture3d = 0x806F,
  GProxyTexture3d = 0x8070,
  GTextureDepth = 0x8071,
  GTextureWrapR = 0x8072,
  GMax3dTextureSize = 0x8073,
  GTextureBinding3d = 0x806A,
  GConstantColor = 0x8001,
  GOneMinusConstantColor = 0x8002,
  GConstantAlpha = 0x8003,
  GOneMinusConstantAlpha = 0x8004,
  GColorTable = 0x80D0,
  GPostConvolutionColorTable = 0x80D1,
  GPostColorMatrixColorTable = 0x80D2,
  GProxyColorTable = 0x80D3,
  GProxyPostConvolutionColorTable = 0x80D4,
  GProxyPostColorMatrixColorTable = 0x80D5,
  GColorTableScale = 0x80D6,
  GColorTableBias = 0x80D7,
  GColorTableFormat = 0x80D8,
  GColorTableWidth = 0x80D9,
  GColorTableRedSize = 0x80DA,
  GColorTableGreenSize = 0x80DB,
  GColorTableBlueSize = 0x80DC,
  GColorTableAlphaSize = 0x80DD,
  GColorTableLuminanceSize = 0x80DE,
  GColorTableIntensitySize = 0x80DF,
  GConvolution1d = 0x8010,
  GConvolution2d = 0x8011,
  GSeparable2d = 0x8012,
  GConvolutionBorderMode = 0x8013,
  GConvolutionFilterScale = 0x8014,
  GConvolutionFilterBias = 0x8015,
  GReduce = 0x8016,
  GConvolutionFormat = 0x8017,
  GConvolutionWidth = 0x8018,
  GConvolutionHeight = 0x8019,
  GMaxConvolutionWidth = 0x801A,
  GMaxConvolutionHeight = 0x801B,
  GPostConvolutionRedScale = 0x801C,
  GPostConvolutionGreenScale = 0x801D,
  GPostConvolutionBlueScale = 0x801E,
  GPostConvolutionAlphaScale = 0x801F,
  GPostConvolutionRedBias = 0x8020,
  GPostConvolutionGreenBias = 0x8021,
  GPostConvolutionBlueBias = 0x8022,
  GPostConvolutionAlphaBias = 0x8023,
  GConstantBorder = 0x8151,
  GReplicateBorder = 0x8153,
  GConvolutionBorderColor = 0x8154,
  GColorMatrix = 0x80B1,
  GColorMatrixStackDepth = 0x80B2,
  GMaxColorMatrixStackDepth = 0x80B3,
  GPostColorMatrixRedScale = 0x80B4,
  GPostColorMatrixGreenScale = 0x80B5,
  GPostColorMatrixBlueScale = 0x80B6,
  GPostColorMatrixAlphaScale = 0x80B7,
  GPostColorMatrixRedBias = 0x80B8,
  GPostColorMatrixGreenBias = 0x80B9,
  GPostColorMatrixBlueBias = 0x80BA,
  GPostColorMatrixAlphaBias = 0x80BB,
  GHistogram = 0x8024,
  GProxyHistogram = 0x8025,
  GHistogramWidth = 0x8026,
  GHistogramFormat = 0x8027,
  GHistogramRedSize = 0x8028,
  GHistogramGreenSize = 0x8029,
  GHistogramBlueSize = 0x802A,
  GHistogramAlphaSize = 0x802B,
  GHistogramLuminanceSize = 0x802C,
  GHistogramSink = 0x802D,
  GMinmax = 0x802E,
  GMinmaxFormat = 0x802F,
  GMinmaxSink = 0x8030,
  GTableTooLarge = 0x8031,
  GBlendEquation = 0x8009,
  GMin = 0x8007,
  GMax = 0x8008,
  GFuncAdd = 0x8006,
  GFuncSubtract = 0x800A,
  GFuncReverseSubtract = 0x800B,
  GBlendColor = 0x8005,
  GTexture0 = 0x84C0,
  GTexture1 = 0x84C1,
  GTexture2 = 0x84C2,
  GTexture3 = 0x84C3,
  GTexture4 = 0x84C4,
  GTexture5 = 0x84C5,
  GTexture6 = 0x84C6,
  GTexture7 = 0x84C7,
  GTexture8 = 0x84C8,
  GTexture9 = 0x84C9,
  GTexture10 = 0x84CA,
  GTexture11 = 0x84CB,
  GTexture12 = 0x84CC,
  GTexture13 = 0x84CD,
  GTexture14 = 0x84CE,
  GTexture15 = 0x84CF,
  GTexture16 = 0x84D0,
  GTexture17 = 0x84D1,
  GTexture18 = 0x84D2,
  GTexture19 = 0x84D3,
  GTexture20 = 0x84D4,
  GTexture21 = 0x84D5,
  GTexture22 = 0x84D6,
  GTexture23 = 0x84D7,
  GTexture24 = 0x84D8,
  GTexture25 = 0x84D9,
  GTexture26 = 0x84DA,
  GTexture27 = 0x84DB,
  GTexture28 = 0x84DC,
  GTexture29 = 0x84DD,
  GTexture30 = 0x84DE,
  GTexture31 = 0x84DF,
  GActiveTexture = 0x84E0,
  GClientActiveTexture = 0x84E1,
  GMaxTextureUnits = 0x84E2,
  GNormalMap = 0x8511,
  GReflectionMap = 0x8512,
  GTextureCubeMap = 0x8513,
  GTextureBindingCubeMap = 0x8514,
  GTextureCubeMapPositiveX = 0x8515,
  GTextureCubeMapNegativeX = 0x8516,
  GTextureCubeMapPositiveY = 0x8517,
  GTextureCubeMapNegativeY = 0x8518,
  GTextureCubeMapPositiveZ = 0x8519,
  GTextureCubeMapNegativeZ = 0x851A,
  GProxyTextureCubeMap = 0x851B,
  GMaxCubeMapTextureSize = 0x851C,
  GCompressedAlpha = 0x84E9,
  GCompressedLuminance = 0x84EA,
  GCompressedLuminanceAlpha = 0x84EB,
  GCompressedIntensity = 0x84EC,
  GCompressedRgb = 0x84ED,
  GCompressedRgba = 0x84EE,
  GTextureCompressionHint = 0x84EF,
  GTextureCompressedImageSize = 0x86A0,
  GTextureCompressed = 0x86A1,
  GNumCompressedTextureFormats = 0x86A2,
  GCompressedTextureFormats = 0x86A3,
  GMultisample = 0x809D,
  GSampleAlphaToCoverage = 0x809E,
  GSampleAlphaToOne = 0x809F,
  GSampleCoverage = 0x80A0,
  GSampleBuffers = 0x80A8,
  GSamples = 0x80A9,
  GSampleCoverageValue = 0x80AA,
  GSampleCoverageInvert = 0x80AB,
  GMultisampleBit = 0x20000000,
  GTransposeModelviewMatrix = 0x84E3,
  GTransposeProjectionMatrix = 0x84E4,
  GTransposeTextureMatrix = 0x84E5,
  GTransposeColorMatrix = 0x84E6,
  GCombine = 0x8570,
  GCombineRgb = 0x8571,
  GCombineAlpha = 0x8572,
  GSource0Rgb = 0x8580,
  GSource1Rgb = 0x8581,
  GSource2Rgb = 0x8582,
  GSource0Alpha = 0x8588,
  GSource1Alpha = 0x8589,
  GSource2Alpha = 0x858A,
  GOperand0Rgb = 0x8590,
  GOperand1Rgb = 0x8591,
  GOperand2Rgb = 0x8592,
  GOperand0Alpha = 0x8598,
  GOperand1Alpha = 0x8599,
  GOperand2Alpha = 0x859A,
  GRgbScale = 0x8573,
  GAddSigned = 0x8574,
  GInterpolate = 0x8575,
  GSubtract = 0x84E7,
  GConstant = 0x8576,
  GPrimaryColor = 0x8577,
  GPrevious = 0x8578,
  GDot3Rgb = 0x86AE,
  GDot3Rgba = 0x86AF,
  GClampToBorder = 0x812D,
  GArbMultitexture = 1,
  GTexture0Arb = 0x84C0,
  GTexture1Arb = 0x84C1,
  GTexture2Arb = 0x84C2,
  GTexture3Arb = 0x84C3,
  GTexture4Arb = 0x84C4,
  GTexture5Arb = 0x84C5,
  GTexture6Arb = 0x84C6,
  GTexture7Arb = 0x84C7,
  GTexture8Arb = 0x84C8,
  GTexture9Arb = 0x84C9,
  GTexture10Arb = 0x84CA,
  GTexture11Arb = 0x84CB,
  GTexture12Arb = 0x84CC,
  GTexture13Arb = 0x84CD,
  GTexture14Arb = 0x84CE,
  GTexture15Arb = 0x84CF,
  GTexture16Arb = 0x84D0,
  GTexture17Arb = 0x84D1,
  GTexture18Arb = 0x84D2,
  GTexture19Arb = 0x84D3,
  GTexture20Arb = 0x84D4,
  GTexture21Arb = 0x84D5,
  GTexture22Arb = 0x84D6,
  GTexture23Arb = 0x84D7,
  GTexture24Arb = 0x84D8,
  GTexture25Arb = 0x84D9,
  GTexture26Arb = 0x84DA,
  GTexture27Arb = 0x84DB,
  GTexture28Arb = 0x84DC,
  GTexture29Arb = 0x84DD,
  GTexture30Arb = 0x84DE,
  GTexture31Arb = 0x84DF,
  GActiveTextureArb = 0x84E0,
  GClientActiveTextureArb = 0x84E1,
  GMaxTextureUnitsArb = 0x84E2,
  GMesaShaderDebug = 1,
  GDebugObjectMesa = 0x8759,
  GDebugPrintMesa = 0x875A,
  GDebugAssertMesa = 0x875B,
  GMesaPackedDepthStencil = 1,
  GDepthStencilMesa = 0x8750,
  GUnsignedInt248Mesa = 0x8751,
  GUnsignedInt824RevMesa = 0x8752,
  GUnsignedShort151Mesa = 0x8753,
  GUnsignedShort115RevMesa = 0x8754,
  GMesaProgramDebug = 1,
  GFragmentProgramPositionMesa = 0x8bb0,
  GFragmentProgramCallbackMesa = 0x8bb1,
  GFragmentProgramCallbackFuncMesa = 0x8bb2,
  GFragmentProgramCallbackDataMesa = 0x8bb3,
  GVertexProgramPositionMesa = 0x8bb4,
  GVertexProgramCallbackMesa = 0x8bb5,
  GVertexProgramCallbackFuncMesa = 0x8bb6,
  GVertexProgramCallbackDataMesa = 0x8bb7,
  GMesaTextureArray = 1,
  GTexture1dArrayExt = 0x8C18,
  GProxyTexture1dArrayExt = 0x8C19,
  GTexture2dArrayExt = 0x8C1A,
  GProxyTexture2dArrayExt = 0x8C1B,
  GTextureBinding1dArrayExt = 0x8C1C,
  GTextureBinding2dArrayExt = 0x8C1D,
  GMaxArrayTextureLayersExt = 0x88FF,
  GFramebufferAttachmentTextureLayerExt = 0x8CD4,
  GAtiBlendEquationSeparate = 1,
  GAlphaBlendEquationAti = 0x883D,
  GOesEglImage = 1,
};
typedef [set] enum glenum glenum_set;
