#ifndef __SDL_VIDEO_FLAGS_H__
#define __SDL_VIDEO_FLAGS_H__

#include "common.h"

#define MLTAG_SDL_WINDOWEVENT_SHOWN (0)
#define MLTAG_SDL_WINDOWEVENT_HIDDEN (1)
#define MLTAG_SDL_WINDOWEVENT_EXPOSED (2)
#define MLTAG_SDL_WINDOWEVENT_MOVED (3)
#define MLTAG_SDL_WINDOWEVENT_RESIZED (4)
#define MLTAG_SDL_WINDOWEVENT_SIZE_CHANGED (5)
#define MLTAG_SDL_WINDOWEVENT_MINIMIZED (6)
#define MLTAG_SDL_WINDOWEVENT_MAXIMIZED (7)
#define MLTAG_SDL_WINDOWEVENT_RESTORED (8)
#define MLTAG_SDL_WINDOWEVENT_ENTER (9)
#define MLTAG_SDL_WINDOWEVENT_LEAVE (10)
#define MLTAG_SDL_WINDOWEVENT_FOCUS_GAINED (11)
#define MLTAG_SDL_WINDOWEVENT_FOCUS_LOST (12)
#define MLTAG_SDL_WINDOWEVENT_CLOSE (13)

extern lookup_info ml_window_event_table[];

#endif /*__SDL_VIDEO_FLAGS_H__*/
