#ifndef __SDL_KEY_TRANS_H__
#define __SDL_KEY_TRANS_H__

#include <caml/mlvalues.h>
#include "common.h"

#define MLTAG_SDLK_BACKSPACE    (0)
#define MLTAG_SDLK_TAB          (1)
#define MLTAG_SDLK_CLEAR        (2)
#define MLTAG_SDLK_RETURN       (3)
#define MLTAG_SDLK_PAUSE        (4)
#define MLTAG_SDLK_ESCAPE       (5)
#define MLTAG_SDLK_SPACE        (6)
#define MLTAG_SDLK_EXCLAIM      (7)
#define MLTAG_SDLK_QUOTEDBL     (8)
#define MLTAG_SDLK_HASH         (9)
#define MLTAG_SDLK_DOLLAR       (10)
#define MLTAG_SDLK_AMPERSAND    (11)
#define MLTAG_SDLK_QUOTE        (12)
#define MLTAG_SDLK_LEFTPAREN    (13)
#define MLTAG_SDLK_RIGHTPAREN   (14)
#define MLTAG_SDLK_ASTERISK     (15)
#define MLTAG_SDLK_PLUS         (16)
#define MLTAG_SDLK_COMMA        (17)
#define MLTAG_SDLK_MINUS        (18)
#define MLTAG_SDLK_PERIOD       (19)
#define MLTAG_SDLK_SLASH        (20)
#define MLTAG_SDLK_0            (21)
#define MLTAG_SDLK_1            (22)
#define MLTAG_SDLK_2            (23)
#define MLTAG_SDLK_3            (24)
#define MLTAG_SDLK_4            (25)
#define MLTAG_SDLK_5            (26)
#define MLTAG_SDLK_6            (27)
#define MLTAG_SDLK_7            (28)
#define MLTAG_SDLK_8            (29)
#define MLTAG_SDLK_9            (30)
#define MLTAG_SDLK_COLON        (31)
#define MLTAG_SDLK_SEMICOLON    (32)
#define MLTAG_SDLK_LESS         (33)
#define MLTAG_SDLK_EQUALS       (34)
#define MLTAG_SDLK_GREATER      (35)
#define MLTAG_SDLK_QUESTION     (36)
#define MLTAG_SDLK_AT           (37)
#define MLTAG_SDLK_LEFTBRACKET  (38)
#define MLTAG_SDLK_BACKSLASH    (39)
#define MLTAG_SDLK_RIGHTBRACKET (40)
#define MLTAG_SDLK_CARET        (41)
#define MLTAG_SDLK_UNDERSCORE   (42)
#define MLTAG_SDLK_BACKQUOTE    (43)
#define MLTAG_SDLK_A            (44)
#define MLTAG_SDLK_B            (45)
#define MLTAG_SDLK_C            (46)
#define MLTAG_SDLK_D            (47)
#define MLTAG_SDLK_E            (48)
#define MLTAG_SDLK_F            (49)
#define MLTAG_SDLK_G            (50)
#define MLTAG_SDLK_H            (51)
#define MLTAG_SDLK_I            (52)
#define MLTAG_SDLK_J            (53)
#define MLTAG_SDLK_K            (54)
#define MLTAG_SDLK_L            (55)
#define MLTAG_SDLK_M            (56)
#define MLTAG_SDLK_N            (57)
#define MLTAG_SDLK_O            (58)
#define MLTAG_SDLK_P            (59)
#define MLTAG_SDLK_Q            (60)
#define MLTAG_SDLK_R            (61)
#define MLTAG_SDLK_S            (62)
#define MLTAG_SDLK_T            (63)
#define MLTAG_SDLK_U            (64)
#define MLTAG_SDLK_V            (65)
#define MLTAG_SDLK_W            (66)
#define MLTAG_SDLK_X            (67)
#define MLTAG_SDLK_Y            (68)
#define MLTAG_SDLK_Z            (69)
#define MLTAG_SDLK_DELETE       (70)
#define MLTAG_SDLK_KP0          (71)
#define MLTAG_SDLK_KP1          (72)
#define MLTAG_SDLK_KP2          (73)
#define MLTAG_SDLK_KP3          (74)
#define MLTAG_SDLK_KP4          (75)
#define MLTAG_SDLK_KP5          (76)
#define MLTAG_SDLK_KP6          (77)
#define MLTAG_SDLK_KP7          (78)
#define MLTAG_SDLK_KP8          (79)
#define MLTAG_SDLK_KP9          (80)
#define MLTAG_SDLK_KP_PERIOD    (81)
#define MLTAG_SDLK_KP_DIVIDE    (82)
#define MLTAG_SDLK_KP_MULTIPLY  (83)
#define MLTAG_SDLK_KP_MINUS     (84)
#define MLTAG_SDLK_KP_PLUS      (85)
#define MLTAG_SDLK_KP_ENTER     (86)
#define MLTAG_SDLK_KP_EQUALS    (87)
#define MLTAG_SDLK_UP           (88)
#define MLTAG_SDLK_DOWN         (89)
#define MLTAG_SDLK_RIGHT        (90)
#define MLTAG_SDLK_LEFT         (91)
#define MLTAG_SDLK_INSERT       (92)
#define MLTAG_SDLK_HOME         (93)
#define MLTAG_SDLK_END          (94)
#define MLTAG_SDLK_PAGEUP       (95)
#define MLTAG_SDLK_PAGEDOWN     (96)
#define MLTAG_SDLK_F1           (97)
#define MLTAG_SDLK_F2           (98)
#define MLTAG_SDLK_F3           (99)
#define MLTAG_SDLK_F4           (100)
#define MLTAG_SDLK_F5           (101)
#define MLTAG_SDLK_F6           (102)
#define MLTAG_SDLK_F7           (103)
#define MLTAG_SDLK_F8           (104)
#define MLTAG_SDLK_F9           (105)
#define MLTAG_SDLK_F10          (106)
#define MLTAG_SDLK_F11          (107)
#define MLTAG_SDLK_F12          (108)
#define MLTAG_SDLK_F13          (109)
#define MLTAG_SDLK_F14          (110)
#define MLTAG_SDLK_F15          (111)
#define MLTAG_SDLK_NUMLOCK      (112)
#define MLTAG_SDLK_CAPSLOCK     (113)
#define MLTAG_SDLK_SCROLLOCK    (114)
#define MLTAG_SDLK_RSHIFT       (115)
#define MLTAG_SDLK_LSHIFT       (116)
#define MLTAG_SDLK_RCTRL        (117)
#define MLTAG_SDLK_LCTRL        (118)
#define MLTAG_SDLK_RALT         (119)
#define MLTAG_SDLK_LALT         (120)
#define MLTAG_SDLK_RMETA        (121)
#define MLTAG_SDLK_LMETA        (122)
#define MLTAG_SDLK_LSUPER       (123)
#define MLTAG_SDLK_RSUPER       (124)
#define MLTAG_SDLK_MODE         (125)
#define MLTAG_SDLK_HELP         (126)
#define MLTAG_SDLK_PRINT        (127)
#define MLTAG_SDLK_SYSREQ       (128)
#define MLTAG_SDLK_BREAK        (129)
#define MLTAG_SDLK_MENU         (130)
#define MLTAG_SDLK_POWER        (131)
#define MLTAG_SDLK_EURO         (132)

/* modify key constants */
#define MLTAG_KMOD_NONE         ( 0)
#define MLTAG_KMOD_NUM          ( 1)
#define MLTAG_KMOD_CAPS         ( 2)
#define MLTAG_KMOD_LCTRL        ( 3)
#define MLTAG_KMOD_RCTRL        ( 4)
#define MLTAG_KMOD_RSHIFT       ( 5)
#define MLTAG_KMOD_LSHIFT       ( 6)
#define MLTAG_KMOD_RALT         ( 7)
#define MLTAG_KMOD_LALT         ( 8)
#define MLTAG_KMOD_CTRL         ( 9)
#define MLTAG_KMOD_SHIFT        (10)
#define MLTAG_KMOD_ALT          (11)


extern lookup_info ml_symkey_trans_table[];
extern lookup_info ml_modkey_trans_table[];

#endif /*__SDL_KEY_TRANS_H__*/
