#include "sdl_initflags.h"

#include <SDL.h>

lookup_info ml_init_flag_table[] = {
{0, 8},
{MLTAG_TIMER, SDL_INIT_TIMER},
{MLTAG_VIDEO, SDL_INIT_VIDEO},
{MLTAG_AUDIO, SDL_INIT_AUDIO},
{MLTAG_CDROM, SDL_INIT_CDROM},
{MLTAG_JOYSTICK, SDL_INIT_JOYSTICK},
{MLTAG_EVENTTHREAD, SDL_INIT_EVENTTHREAD},
{MLTAG_NOPARACHUTE, SDL_INIT_NOPARACHUTE},
{MLTAG_EVERYTHING, SDL_INIT_EVERYTHING}
};
